sensors:
#RIGHT BIN CAMERAS
  right_bins_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]
  right_bins_rgb_camera:
    type: rgb_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, 3.03, 1.8]
      rpy: [0, pi/2, 0]

#LEFT BIN CAMERAS
  left_bins_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]
  left_bins_rgb_camera:
    visualize_fov: true
    type: rgb_camera
    pose:
      xyz: [-2.286, -2.89, 1.8]
      rpy: [0, pi/2, 0]

#LEFT TRAY CAMERAS
  kts1_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  # kts1_rgb_camera:
  #   type: rgb_camera
  #   visualize_fov: true
  #   pose:
  #     xyz: [-1.30, -5.8, 1.5]  
  #     rpy: [pi, pi/2, pi/2]

#RIGHT TRAY CAMERAS
  kts2_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]
  # kts2_rgb_camera:
  #   visualize_fov: true
  #   type: rgb_camera
  #   pose:
  #     xyz: [-1.30, 5.8, 1.5]
  #     rpy: [pi, pi/2, -pi/2]